
spring:
  thymeleaf:
    prefix:
      classpath: /templates   # 访问template下的html文件需要配置模板，映射
    cache: false # 开发时关闭缓存,不然没法看到实时页面
  jackson:
    time-zone: GMT+8
  #切面启用
  aop:
    proxy-target-class: false		#默认为false
    auto: true		#默认为false
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      #123.56.71.68。123.56.71.68。123.56.71.68。123.56.71.68
      url: jdbc:mysql://localhost:3306/yuele_weixin?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: A156423djh
      driver-class-name: com.mysql.cj.jdbc.Driver
      druid:
        initialSize: 5
        minIdle: 10
        maxActive: 20
        maxWait: 60000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
  redis:
    host: 127.0.0.1
    password: 31415926
    database: 8
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-wait: 5000
        max-idle: 10
        min-idle: 0
  application:
    name: eureka-client-yueleWeixin-shop
# 阿里云存储参数配置
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com_WANGRUI
    accessKeyId: LTAI5tDb1x6U6KYUUJ7eFGvU_WANGRUI
    accessKeySecret: e1IT1h3yBDJqmMNZ7sMba7R3HNHOiZ_WANGRUI
    bucketName: my-flower-shop_WANGRUI


server:
  port: 9002

eureka:
  client:
    service-url:
      # 服务端的注册地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,,http://eureka7003.com:7003/eureka/