
spring:
  jackson:
    time-zone: GMT+8

  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/yuele_weixin?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      druid:
        initialSize: 5
        minIdle: 10
        maxActive: 20
        maxWait: 60000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
  redis:
    host: 123.56.71.68
    password: 31415926
    database: 8
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-wait: 5000
        max-idle: 10
        min-idle: 0
  application:
    name: eureka-client-yueleWeixin-shop
# 阿里云存储参数配置
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tDb1x6U6KYUUJ7eFGvU
    accessKeySecret: e1IT1h3yBDJqmMNZ7sMba7R3HNHOiZ
    bucketName: my-flower-shop


server:
  port: 9002

eureka:
  client:
    service-url:
      # 服务端的注册地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,,http://eureka7003.com:7003/eureka/